"""
PolyglotLink Utilities

Common utilities for configuration, logging, validation, and error handling.
"""

from polyglotlink.utils.config import (
    Settings,
    get_settings,
    reload_settings,
)
from polyglotlink.utils.exceptions import (
    CacheError,
    ConceptExistsError,
    ConceptNotFoundError,
    ConfigurationError,
    ConversionError,
    DatabaseError,
    EmbeddingError,
    LLMError,
    MappingNotFoundError,
    MessageParseError,
    MissingConfigurationError,
    NormalizationError,
    OntologyError,
    OutputError,
    PolyglotLinkError,
    ProtocolError,
    PublishError,
    SchemaError,
    SchemaExtractionError,
    StorageError,
    TranslationError,
    TypeCoercionError,
    UnsafeFormulaError,
    UnsupportedEncodingError,
    ValidationError,
)
from polyglotlink.utils.logging import (
    LogContext,
    MetricsLogger,
    configure_logging,
    get_logger,
    log_performance,
)
from polyglotlink.utils.validation import (
    detect_malicious_patterns,
    sanitize_dict_keys,
    sanitize_identifier,
    sanitize_string,
    sanitize_topic,
    validate_confidence,
    validate_field_type,
    validate_json_depth,
    validate_json_size,
    validate_number,
    validate_payload_size,
    validate_protocol,
)

__all__ = [
    # Config
    "Settings",
    "get_settings",
    "reload_settings",
    # Exceptions
    "CacheError",
    "ConceptExistsError",
    "ConceptNotFoundError",
    "ConfigurationError",
    "ConversionError",
    "DatabaseError",
    "EmbeddingError",
    "LLMError",
    "MappingNotFoundError",
    "MessageParseError",
    "MissingConfigurationError",
    "NormalizationError",
    "OntologyError",
    "OutputError",
    "PolyglotLinkError",
    "ProtocolError",
    "PublishError",
    "SchemaError",
    "SchemaExtractionError",
    "StorageError",
    "TranslationError",
    "TypeCoercionError",
    "UnsafeFormulaError",
    "UnsupportedEncodingError",
    "ValidationError",
    # Logging
    "LogContext",
    "MetricsLogger",
    "configure_logging",
    "get_logger",
    "log_performance",
    # Validation
    "detect_malicious_patterns",
    "sanitize_dict_keys",
    "sanitize_identifier",
    "sanitize_string",
    "sanitize_topic",
    "validate_confidence",
    "validate_field_type",
    "validate_json_depth",
    "validate_json_size",
    "validate_number",
    "validate_payload_size",
    "validate_protocol",
]
